enum SettingActionType {
    SETTING_LOADING_PAGE = "SETTING_LOADING_PAGE",
    SETTING_RESPONSE_PAGE = "SETTING_RESPONSE_PAGE",
    SETTING_SET_RESPONSE_PAGE = "SETTING_SET_RESPONSE_PAGE",
    SETTING_SET_ALERT = "SETTING_SET_ALERT",
}

export { SettingActionType }